use super::{GameInstanceAdapter, InstanceReport, LaunchAssignment};
use erps_proto::v1::{self as pb, game_server_service_client::GameServerServiceClient};
use std::{sync::Arc,time::Duration};
use tokio::{sync::mpsc,time::sleep};
use tokio_stream::wrappers::ReceiverStream;
use tonic::transport::Channel;

#[derive(Clone,Debug)]
pub struct ErpsServerConfig { pub endpoint:String,pub auth_token:String,pub server_id:String,pub generation:u64,pub game_endpoint:String,pub region:String,pub capacity_total:u32,pub max_instances:u32,pub mode_costs:Vec<(i32,u32)>,pub heartbeat:Duration }

pub struct ErpsGameServerClient<A:GameInstanceAdapter>{config:ErpsServerConfig,adapter:Arc<A>}
impl<A:GameInstanceAdapter> ErpsGameServerClient<A>{
 pub fn new(config:ErpsServerConfig,adapter:Arc<A>)->Self{Self{config,adapter}}
 pub async fn run(self)->Result<(),tonic::Status>{let mut backoff=Duration::from_millis(100);loop{match self.run_connection().await{Ok(())=>backoff=Duration::from_millis(100),Err(status)=>{if !matches!(status.code(),tonic::Code::Unavailable|tonic::Code::Cancelled|tonic::Code::Unknown){return Err(status)}}}sleep(backoff).await;backoff=(backoff*2).min(Duration::from_secs(5));}}
 async fn run_connection(&self)->Result<(),tonic::Status>{let channel=Channel::from_shared(self.config.endpoint.clone()).map_err(|e|tonic::Status::invalid_argument(e.to_string()))?.connect().await.map_err(|e|tonic::Status::unavailable(e.to_string()))?;let mut rpc=GameServerServiceClient::new(channel);let register=pb::RegisterServerRequest{api:Some(api()),auth_token:self.config.auth_token.clone(),server_id:self.config.server_id.clone(),generation:self.config.generation,endpoint:self.config.game_endpoint.clone(),region:self.config.region.clone(),capacity_total:self.config.capacity_total,max_instances:self.config.max_instances,mode_costs:self.config.mode_costs.iter().map(|(mode,cost)|pb::ModeCost{mode:*mode,cost:*cost}).collect(),instances:self.instances()};let result=rpc.register(register).await?.into_inner();if !result.accepted{return Err(tonic::Status::failed_precondition(result.code))}rpc.reconcile_instances(pb::ReconcileRequest{server_id:self.config.server_id.clone(),generation:self.config.generation,instances:self.instances()}).await?;let(tx,rx)=mpsc::channel(64);let mut controls=rpc.control_stream(ReceiverStream::new(rx)).await?.into_inner();let identity=(self.config.server_id.clone(),self.config.generation);let heartbeat=self.config.heartbeat;let heartbeats=tx.clone();let adapter=self.adapter.clone();tokio::spawn(async move{let mut ticker=tokio::time::interval(heartbeat);loop{ticker.tick().await;let snapshot=adapter.snapshot();if heartbeats.send(pb::ServerControl{server_id:identity.0.clone(),generation:identity.1,message:Some(pb::server_control::Message::Heartbeat(pb::Heartbeat{capacity_used:snapshot.iter().map(|v|v.reserved_cost).sum(),running_instances:snapshot.iter().filter(|v|v.state.eq_ignore_ascii_case("running")).count()as u32}))}).await.is_err(){break}for instance in snapshot{if heartbeats.send(pb::ServerControl{server_id:identity.0.clone(),generation:identity.1,message:Some(pb::server_control::Message::Instance(pb::InstanceState{match_id:instance.match_id,state:instance.state,reserved_cost:instance.reserved_cost}))}).await.is_err(){return}}}});while let Some(control)=controls.message().await?{if let Some(pb::erps_control::Message::Launch(launch))=control.message{let match_id=launch.match_id.clone();let assignment=LaunchAssignment::from(launch);let result=self.adapter.launch(assignment);let(state,endpoint,connection_token,reason)=match result{Ok(ready)=>("ready".into(),ready.endpoint,ready.connection_token,String::new()),Err(reason)=>("rejected".into(),String::new(),String::new(),reason)};tx.send(pb::ServerControl{server_id:self.config.server_id.clone(),generation:self.config.generation,message:Some(pb::server_control::Message::LaunchResult(pb::LaunchResult{match_id,state,endpoint,connection_token,reason}))}).await.map_err(|_|tonic::Status::unavailable("control stream closed"))?;}}Ok(())}
 fn instances(&self)->Vec<pb::InstanceState>{self.adapter.snapshot().into_iter().map(|v:InstanceReport|pb::InstanceState{match_id:v.match_id,state:v.state,reserved_cost:v.reserved_cost}).collect()}
}
fn api()->pb::ApiVersion{pb::ApiVersion{major:1,minor:0,capabilities:vec!["reconcile".into()]}}

#[cfg(test)]mod tests{use super::*;#[test]fn feature_config_supports_one_to_one_hundred_instances(){for v in[1,100]{let c=ErpsServerConfig{endpoint:"http://127.0.0.1:1".into(),auth_token:"x".into(),server_id:"x".into(),generation:1,game_endpoint:"127.0.0.1:2".into(),region:"tw".into(),capacity_total:100,max_instances:v,mode_costs:vec![],heartbeat:Duration::from_secs(2)};assert!((1..=100).contains(&c.max_instances));}}}
