# 連結器配置範例

# === 選項 1: 使用 mold (最快) ===
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# === 選項 2: 使用 lld (次快) ===
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# === 選項 3: 使用 mold 但保留調試信息 ===
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = [
#     "-C", "link-arg=-fuse-ld=mold",
#     "-C", "link-arg=-Wl,--compress-debug-sections=zlib",
# ]

[build]
jobs = 6

[profile.dev]
opt-level = 0
debug = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3
debug = false