//! Lockstep wire layer (Phase 2 scaffolding).
//!
//! Runs alongside the legacy 30Hz GameEvent dispatcher. Phase 2 only handles
//! input buffering and 60Hz TickBatch broadcast; the simulation itself stays
//! on the existing 30Hz pipeline. Phase 3 will move sim execution into this
//! lockstep loop, and Phase 4 will retire the legacy GameEvent broadcast.
//!
//! This module is gated behind `#[cfg(feature = "kcp")]` because it depends on
//! the prost-generated proto types that only build under the kcp feature.

pub mod input_buffer;
pub mod tick_broadcaster;
pub mod state;

pub use self::input_buffer::InputBuffer;
pub use self::tick_broadcaster::{TickBroadcaster, TickBroadcasterConfig};
pub use self::state::{LockstepState, PlayerSession, JoinRoleEnum};

// Re-export proto types used by this module so callers don't need
// to know the prost-generated path. Proto types live under
// `crate::transport::kcp_transport::game_proto` (see kcp_transport.rs:18).
pub use crate::transport::kcp_transport::game_proto::{
    PlayerInput,
    InputSubmit,
    TickBatch,
    InputForPlayer,
    StateHash,
    JoinRequest,
    JoinRole,
    GameStart,
    SnapshotReq,
    SnapshotResp,
    SimSnapshot,
    ServerEvent,
    Vec2I,
    FixedI,
    AngleI,
    NoOp,
    MoveTo,
    AttackTarget,
    CastAbility,
    TowerPlace,
    TowerUpgradeInput,
    TowerSell,
    ItemUse,
    PlayerJoinEvent,
    PlayerLeaveEvent,
    WaveStartEvent,
    GameEndEvent,
};

// The PlayerInput oneof inner enum is generated by prost as
// `mod player_input { pub enum Action { NoOp(...), MoveTo(...), ... } }`.
// Re-export as `PlayerInputEnum` for ergonomic construction.
pub use crate::transport::kcp_transport::game_proto::player_input::Action as PlayerInputEnum;

// Likewise the ServerEvent oneof inner enum.
pub use crate::transport::kcp_transport::game_proto::server_event::Event as ServerEventEnum;

/// Lockstep wire frame variants — broadcast targets selected by the
/// kcp_transport thread. Phase 2 introduces 4 frame types:
///
/// - `TickBatch`     (tag 0x11, S→C, broadcast All)
/// - `StateHash`     (tag 0x12, S→C, broadcast All)
/// - `GameStart`     (tag 0x14, S→C, single client)
/// - `SnapshotResp`  (tag 0x16, S→C, single client)
///
/// `OutboundMsg` carries this in a new `Option<LockstepFrame>` field; when
/// present, the kcp broadcast thread (Task 2.3) emits the corresponding
/// framed payload directly, bypassing the GameEvent envelope. Legacy
/// `OutboundMsg` (typed/JSON) flow is unchanged.
#[derive(Clone, Debug)]
pub enum LockstepFrame {
    /// 60Hz broadcast to every connected lockstep client.
    TickBatch(TickBatch),
    /// Periodic desync probe — broadcast to all.
    StateHash(StateHash),
    /// Per-client response to JoinRequest. `client_session_id` matches the
    /// kcp transport's session map key (e.g. `kcp_<addr>`).
    GameStart {
        client_session_id: String,
        msg: GameStart,
    },
    /// Per-client snapshot reply.
    SnapshotResp {
        client_session_id: String,
        msg: SnapshotResp,
    },
}
